# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter

gem "rspec", ">=0"
gem "pry", ">=0"

gem "rdoc", "~>3.10", :group => [:development, :test]
gem "hoe", "~>3.0", :group => [:development, :test]

# vim: syntax=ruby
